name: Build a simple deb package

on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
    - name: 读取当前版本号
      id: version
      uses: ashley-taylor/read-json-property-action@v1.0
      with:
        path: ./package.json
        property: version

    - name: 7. 读取描述文件
      id: description
      uses: juliangruber/read-file-action@v1
      with:
        path: ./description.txt

    - name: build package
      run: |
        ls -al
        echo ${{steps.version.outputs.value}}
        export VERSION=${{ github.ref }}
        export MSG=$(git log -n 1 --pretty=format:' %s')
        echo version is ${VERSION}, msg is ${MSG}
        # docker run --rm -v ${PWD}:/root/simple-deb kaylor/ubuntu:simple_deb_env sh -c "export EMAIL=kaylor.chen@qq.com && cd /root/simple-deb && rm -rf debian/changelog && dch --create --package=simple-deb -v ${VERSION} ${MSG} && fakeroot debian/rules clean && fakeroot debian/rules binary && mv ../simple-deb*.deb ./"
        docker run --rm -v ${PWD}:/root/simple-deb kaylor/ubuntu:simple_deb_env sh -c "export EMAIL=kaylor.chen@qq.com && cd /root/simple-deb && fakeroot debian/rules clean && fakeroot debian/rules binary && mv ../simple-deb*.deb ./"
        ls -al