name: Build a simple deb package

env:
  CHANGELOG_AUTHOR_NAME: "Kaylor"
  CHANGELOG_AUTHOR_EMAIL: "kaylor.chen@qq.com"

on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Patch changelog (snapshot)
      uses: pi-top/git-debian-changelog-bump-action@master
      with:
        release: false
        author_name: ${{ env.CHANGELOG_AUTHOR_NAME }}
        author_email: ${{ env.CHANGELOG_AUTHOR_EMAIL }}
        
    - name: Determine current version
      run: |
        sudo apt install -y dpkg-dev
        echo "CURRENT_VERSION=$(dpkg-parsechangelog -Sversion)" >> $GITHUB_ENV
        echo $GITHUB_ENV


    # - name: Get version
    #   id: get_version
    #   run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

    # - name: build package
    #   run: |
    #     ls -al
    #     export VERSION=${{steps.version.outputs.VERSION}}
    #     export MSG=$(git log -n 1 --pretty=format:' %s')
    #     echo version is ${VERSION}, msg is ${MSG}
    #     # docker run --rm -v ${PWD}:/root/simple-deb kaylor/ubuntu:simple_deb_env sh -c "export EMAIL=kaylor.chen@qq.com && cd /root/simple-deb && rm -rf debian/changelog && dch --create --package=simple-deb -v ${VERSION} ${MSG} && fakeroot debian/rules clean && fakeroot debian/rules binary && mv ../simple-deb*.deb ./"
    #     docker run --rm -v ${PWD}:/root/simple-deb kaylor/ubuntu:simple_deb_env sh -c "export EMAIL=kaylor.chen@qq.com && cd /root/simple-deb && fakeroot debian/rules clean && fakeroot debian/rules binary && mv ../simple-deb*.deb ./"
    #     ls -al
