name: Build a simple deb package with arm64 docker

env:
  CHANGELOG_AUTHOR_NAME: "Kaylor"
  CHANGELOG_AUTHOR_EMAIL: "kaylor.chen@qq.com"

on:
  push:
    branches:
    - arm64
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, armv7]
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: build package
      run: |
        echo "Runner architecture is ${{matrix.arch}}"
        ls -al
        export VERSION=$(git describe --tags)
        export MSG=$(git log -n 1 --pretty=format:' %s')
        echo version is ${VERSION}, msg is ${MSG}
        docker run --rm -v ${PWD}:/root/simple-deb kaylor/ubuntu_arm64_humble_env:base sh -c "export EMAIL=kaylor.chen@qq.com && cd /root/simple-deb && dch -v ${VERSION} ${MSG} && fakeroot debian/rules clean && fakeroot debian/rules binary && mv ../simple-deb*.deb ./"
        ls -al
        rm -rf ./artifact
        mkdir -p ./artifact
        cp simple-deb*.deb ./artifact

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: simple_deb
        path: ./artifact/
